version: '3.7'
services:
  db:
    #image: mysql:5.7
    image: mariadb:latest
    volumes:
        - db_data:/var/lib/mysql
    restart: always
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: test123
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test123
  
  jupyter:
    image: jupyter/base-notebook
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./schemas:/home/jovyan/work/schemas
  
volumes:
  db_data:
  notebooks:
  schemas:
